name: Commit to WordPress SVN

on:
  push:
    branches: [ master ]

jobs:
  commit:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: svn pull
        run: |
          mkdir svn
          cd svn
          svn co http://plugins.svn.wordpress.org/calj/
